# Site settings
title: 🥂 Nicky & David - 20190113 Let's celebrate!
email: me+nicky@davidng.hk
url: https://nickyAnd.davidng.hk
description: "Celebrating Nicky and David's wedding on 13 Jan 2019."
hero-title: We're getting married!
hero-description: Nicky & David are getting married on 13 Jan 2019. <br> We would like you to be a part of it.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ffb3b3'
  primary-pink: '#ffb3a7'

# Footer settings
footer: <i class="fa fa-heart"></i> With love, Nicky & David

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/david90

# Build settings
markdown: kramdown
permalink: pretty
